# Generated by Django 4.2.6 on 2023-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('price', models.CharField(max_length=240, verbose_name='Price')),
                ('dateAdded', models.DateField(auto_now_add=True, verbose_name='Date added')),
            ],
        ),
    ]
