# Generated by Django 4.2.6 on 2023-10-28 16:31

from django.db import migrations

def create_data(apps, schema_editor):
    Product = apps.get_model('prices', 'Product')
    Product(name="Fish Tank", price="44.99").save()



class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_prices'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
