# Generated by Django 4.2.6 on 2023-10-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_prices'),
        ('prices', '0004_prices'),
    ]

    operations = [
    ]
