# Generated by Django 4.2.6 on 2023-11-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0005_merge_0003_prices_0004_prices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="amazonURL",
            field=models.URLField(default=9.99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="amzCurrentPrice",
            field=models.DecimalField(decimal_places=2, default=8.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="amzMSRP",
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="img",
            field=models.CharField(
                default="imgs/test.jpeg", max_length=240, verbose_name="Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="lowestPrice",
            field=models.DecimalField(decimal_places=2, default=8.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="walCurrentPrice",
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="walMSRP",
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="walmartURL",
            field=models.URLField(
                default="https://www.walmart.com/ip/Pedigree-Complete-Nutrition-Roasted-Chicken-Rice-Vegetable-Dry-Dog-Food-For-Adult-Dog-18-Lb-Bag/365811940?athbdg=L1102&from=/search"
            ),
            preserve_default=False,
        ),
    ]
