# Generated by Django 4.2.6 on 2023-11-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0006_remove_product_price_product_amazonurl_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="walmartURL",
            new_name="walURL",
        ),
    ]
