# Generated by Django 4.2.6 on 2023-11-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0007_rename_walmarturl_product_walurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="amazonURL",
            new_name="amzURL",
        ),
    ]
