# Generated by Django 4.2.6 on 2023-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_rename_amazonurl_product_amzurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=240, verbose_name='Username')),
                ('password', models.CharField(max_length=240, verbose_name='Password')),
                ('email', models.CharField(max_length=240, verbose_name='Email')),
                ('joinDate', models.DateField(auto_now_add=True, verbose_name='Join Date')),
            ],
        ),
    ]
