# Generated by Django 4.2.6 on 2023-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0008_rename_amazonurl_product_amzurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
