# Generated by Django 4.2.6 on 2023-11-25 05:01

from django.db import migrations

def create_data(apps, schema_editor):
    Product = apps.get_model('prices', 'Product')
    Product(userName="JohnDoe", password="foobar", email="jdoe@ric.edu").save()



class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_user'),
    ]

    operations = [
    ]
